### ISSUE TITLE
Modificação e alteração da documentação.

### ISSUE THREAD

**Issue by Yuri-sc** [Yuri-sc/Consultoriodeestetica-TCC#6]
Modificação e alteração da documentação para a conclusão de tal.

- [x] Estudo de caso | 2.1 Problemática
- [x] Introdução
- [x] Experimento | 3.1
- [x] Referências

**Comment by nicolembecker** [comment]
[nova documentação.docx](https://github.com/Yuri-sc/Consultoriodeestetica-TCC/files/7003608/nova.documentacao.docx)

**Comment by nicolembecker** [comment]
*Algumas mudanças ainda são necessárias como a decisão de como iremos mencionar o sistema e como iremos nos referirmos a ele.
